### PR TITLE
Update Symfony YAML version

### PR DESCRIPTION
**Pull request by ptlis**
Allows this library to work with Symfony 4+ components.

### CODE REVIEW

**Comment by ptlis** [comment]
The two failures are due to Travis no longer supporting PHP5.3 - I didn't want change the Travis config file in this PR as it's unrelated to the change I made.

**Comment by philiplb** [comment]
+1

**Comment by philiplb** [comment]
@romaricdrigon Any chance this could get merged?

**Comment by romaricdrigon** [comment]
Sure. I will have to fix Travis, remove PHP5.3, and then I will merge that. I may need a few days to work on everything.

**Comment by philiplb** [comment]
Hi,
sry to bother again, but this is the only thing keeping me from releasing a new version of https://github.com/philiplb/CRUDlex . :)
Currently, I have to add the repository of the fork to my configuration and

```JS
    "minimum-stability": "dev",
    "prefer-stable": true
```

which is not so nice.

**Comment by romaricdrigon** [comment]
Thank you for the reminder, I will work on that right now!

**Comment by philiplb** [comment]
Thank you so much. :)

**Comment by romaricdrigon** [comment]
Thank you for your PR? sorry it was a busy week and it slipped out of my mind!

**Comment by romaricdrigon** [comment]
I'm merging to a local branch, checking if it works, and then it will be released!
@philiplb for now you will have to use `@dev` version, or a precise commit hash. I want to have a look at other PRs & add PHP7 to the build matrix, then I will tag a new version soon!

**Comment by philiplb** [comment]
@romaricdrigon Alright, great, that will do it. :) Thank you!

**Comment by romaricdrigon** [comment]
#17 is now merged to master, thank you @philiplb and @ptlis

**Comment by philiplb** [comment]
Thank you for this library. :-)

**Pull request merged**
